// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpcwwcjxolrjlqdzpkuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndwY3d3Y2p4b2xyamxxZHpwa3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTk0NTUsImV4cCI6MjA3MjkzNTQ1NX0.IXgX-8LlWt8O0fzAiwQChKnRGbc7a_8q3pHZ05BO1Og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});